=== CONTENIDO/CONTENIDO/setup/installsettings.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT setup (db, path, client, admin_user, advanced?)>
        <!ELEMENT db (host, user, password, database, charset, engine, collation, prefix, option_mysqli_init_command)>
        <!ELEMENT path (http_root_path)>
        <!ELEMENT client (client_mode)>
        <!ELEMENT admin_user (password, email)>

        <!ELEMENT host (#PCDATA)>
        <!ELEMENT user (#PCDATA)>
        <!ELEMENT password (#PCDATA)>
        <!ELEMENT database (#PCDATA)>
        <!ELEMENT charset (#PCDATA)>
        <!ELEMENT prefix (#PCDATA)>
        <!ELEMENT engine (#PCDATA)>
        <!ELEMENT collation (#PCDATA)>
        <!ELEMENT option_mysqli_init_command (#PCDATA)>

        <!ELEMENT http_root_path (#PCDATA)>

        <!ELEMENT client_mode (#PCDATA)>

        <!ELEMENT email (#PCDATA)>

        <!ELEMENT advanced (delete_database)>
        <!ELEMENT delete_database (#PCDATA)>

=== CONTENIDO/CONTENIDO/setup/autoinstall-example.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE setup SYSTEM "installsettings.dtd">
<!-- For a more detailed documentation see the autoinstall-example.ini
The configurable settings are mostly the same -->
<setup>
    <db>
        <host>
            HOST_NAME
        </host>
        <user>
            USER
        </user>
        <password>
            PASSWORD
        </password>
        <database>
            DATABASE_NAME
        </database>
        <charset>
            DATABASE_CHARSET
        </charset>
        <collation>DATABASE_COLLATION</collation>
        <prefix>
            DATABASE_PREFIX
        </prefix>
    </db>

    <path>
        <http_root_path>
            CONTENIDO_WEB_ROOT
        </http_root_path>
    </path>

    <client>
        <client_mode>
            CLIENTEXAMPLES
        </client_mode>
    </client>

    <admin_user>
        <password>
            SYSADMIN_PASSWORD
        </password>
        <email>
            SYSADMIN_EMAIL
        </email>
    </admin_user>
</setup>
